### ISSUE TITLE
Composer version is too low

### ISSUE THREAD

**Issue by skorpi** [Flowpack/Flowpack.Behat#13]
With behat version 2.4 the tests in the neos package don't work. The version should be updated accordingly to the versions in the neos distribution (https://git.typo3.org/Neos/Distributions/Base.git/blob/HEAD:/Build/Behat/composer.json).

**Comment by kdambekalns** [comment]
This repository has been moved to [neos/behat](https://github.com/neos/behat) and is archived. This issue is thus being closed. If you feel it should still be taken care of, please open a [new issue in neos/behat](https://github.com/neos/behat/issues/new).
