### ISSUE TITLE
Old guette driver due to not specified version in composer json

### ISSUE THREAD

**Issue by kaystrobach** [Flowpack/Flowpack.Behat#19]
See https://github.com/minkphp/MinkGoutteDriver/issues/56#issuecomment-67766528 for details, basicly the composer json has to be changed a bit to reflect the new versions, otherwise checkbox behaviour can't be tested reliable

```
use behat/mink ~1.6
use behat/mink-goutte-driver ~1.1
```

**Comment by kaystrobach** [comment]
that's how my composer.json looks:
```
{
	"require": {
		"behat/behat": "2.4.*",
		"behat/mink": "~1.6",
		"behat/mink-goutte-driver": "~1.1",
		"behat/mink-selenium2-driver": "*"
	},
	"config": {
		"bin-dir": "../../bin/"
	}
```

**Comment by kdambekalns** [comment]
This repository has been moved to [neos/behat](https://github.com/neos/behat) and is archived. This issue is thus being closed. If you feel it should still be taken care of, please open a [new issue in neos/behat](https://github.com/neos/behat/issues/new).
