### ISSUE TITLE
Saucelabs setup

### ISSUE THREAD

**Issue by sbruggmann** [Flowpack/Flowpack.Behat#20]
How is the correct Setup to use Behat with Saucelabs?
The headless scenarios with Behat works, but scenarios marked mit `@javascript` ends up with the message:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized options "saucelabs" under "behat.extensions.behat_minkextension_extension"
```

**Comment by kdambekalns** [comment]
This repository has been moved to [neos/behat](https://github.com/neos/behat) and is archived. This issue is thus being closed. If you feel it should still be taken care of, please open a [new issue in neos/behat](https://github.com/neos/behat/issues/new).
