### ISSUE TITLE
consoleLoggingCaptureAspect not injected

### ISSUE THREAD

**Issue by mrimann** [Flowpack/Flowpack.Behat#26]
After updating from v2.4.0 to v2.4.1 today, I've ran into the following issue when executing the tests:

```PHP Fatal error:  Call to a member function disableOutput() on a non-object in /var/www/XYZ/Packages/Application/Flowpack.Behat/Tests/Behat/FlowContext.php on line 99```

This happens while resetting the fixtures via a CLI command within the to-be-tested application package which is executed like:

```
	/**
	 * Resets the database and creates some basic data set for testing
	 *
	 * @BeforeScenario
	 */
	public function resetFixtures() {
		$this->flowContext->iRunTheCommand('foo.bar:testing:resetapplicationfortesting');
	}
```

**Comment by hlubek** [comment]
Hi Mario,

it seems the `consoleLoggingCaptureAspect` is not correctly initialized because it's injected in the Behat context (which cannot work IMHO). I'll have a look.

**Comment by hlubek** [comment]
Hi Mario,

I justed fixed the step definition in master. Could you check if this fixes your test? If yes, I'd tag a new release.

**Comment by mrimann** [comment]
Tested and found to be fixed - thanks for the quick fix!
