### ISSUE TITLE
Rename behat:kickstart CLI parameter

### ISSUE THREAD

**Issue by mrimann** [Flowpack/Flowpack.Behat#27]
Follow up to #22 to rename the command line parameter from "package-name" to "package-key" as wished by @hlubek

**Comment by kdambekalns** [comment]
This repository has been moved to [neos/behat](https://github.com/neos/behat) and is archived. This issue is thus being closed. If you feel it should still be taken care of, please open a [new issue in neos/behat](https://github.com/neos/behat/issues/new).
