### ISSUE TITLE
Mac compatibility (wget)

### ISSUE THREAD

**Issue by Robotic-Brain** [Flowpack/Flowpack.Behat#30]
Hi,

I'm just getting started with behat and noticed a small "bug":
The behat:setup command depends on wget, which is not supported on any Mac OS X version

I would just change it to curl, but I don't know if that would cause some other incompatibilities without auto-detection.

**Comment by hlubek** [comment]
I'd say it could happen that neither is available, depending on the system. We could use pure PHP to download the archive.

**Comment by kdambekalns** [comment]
This repository has been moved to [neos/behat](https://github.com/neos/behat) and is archived. This issue is thus being closed. If you feel it should still be taken care of, please open a [new issue in neos/behat](https://github.com/neos/behat/issues/new).
