### ISSUE TITLE
Reset test fixtures does not work for scenario outlines

### ISSUE THREAD

**Issue by hlubek** [Flowpack/Flowpack.Behat#6]
We have type hint that is too strict in the beforeScenario hook:

<pre>
Exception has been thrown in "beforeScenario" hook, defined in Flowpack\Behat\Tests\Behat\FlowContext::resetTestFixtures()
Catchable Fatal Error: Argument 1 passed to Flowpack\Behat\Tests\Behat\FlowContext::resetTestFixtures() must be an instance of Behat\Behat\Event\ScenarioEvent, instance of Behat\Behat\Event\OutlineExampleEvent 
</pre>

**Comment by kdambekalns** [comment]
This repository has been moved to [neos/behat](https://github.com/neos/behat) and is archived. This issue is thus being closed. If you feel it should still be taken care of, please open a [new issue in neos/behat](https://github.com/neos/behat/issues/new).
